name: shared_presentation
description: Shared Presentation Module
publish_to: none
version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  ## packages
  fluttertoast: 8.0.9
  flutter_svg: ^0.21.0
  cached_network_image: ^3.2.0

  ## infrastructure
  common_dependencies:
    path: ../../infrastructure/common_dependencies/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0